<a href="https://colab.research.google.com/github/SandumiJay/FoodPreference/blob/main/DataPreProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [26]:
dataset = pd.read_csv('Food_Preference.csv')
X = dataset.iloc[:, 2:-1].values
Y = dataset.iloc[:, -1].values

In [27]:
print(dataset)

                        Timestamp Participant_ID  Gender Nationality  Age  \
0     2019/05/07 2:59:13 PM GMT+8         FPS001    Male      Indian   24   
1     2019/05/07 2:59:45 PM GMT+8         FPS002  Female      Indian   22   
2     2019/05/07 3:00:05 PM GMT+8         FPS003    Male      Indian   31   
3     2019/05/07 3:00:11 PM GMT+8         FPS004  Female      Indian   25   
4     2019/05/07 3:02:50 PM GMT+8         FPS005    Male      Indian   27   
..                            ...            ...     ...         ...  ...   
283   2019/05/10 9:24:00 AM GMT+8         FPS284    Male      Indian   27   
284   2019/05/10 9:32:54 AM GMT+8         FPS285    Male      Indian   24   
285  2019/05/10 12:09:17 PM GMT+8         FPS286    Male      Indian   25   
286  2019/05/10 12:52:17 PM GMT+8         FPS287    Male      Indian   27   
287  2019/05/10 12:55:42 PM GMT+8         FPS288    Male      Indian   27   

                 Food              Juice Dessert  
0    Traditional food   

In [15]:
print(X)

[['Male' 'Indian' 24 'Traditional food' 'Fresh Juice']
 ['Female' 'Indian' 22 'Western Food' 'Carbonated drinks']
 ['Male' 'Indian' 31 'Western Food' 'Fresh Juice']
 ...
 ['Male' 'Indian' 25 'Traditional food' 'Fresh Juice']
 ['Male' 'Indian' 27 'Traditional food' 'Fresh Juice']
 ['Male' 'Indian' 27 'Traditional food' 'Fresh Juice']]


In [16]:
print(Y)

['Maybe' 'Yes' 'Maybe' 'Maybe' 'Maybe' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No'
 'Yes' 'Maybe' 'Yes' 'Yes' 'Maybe' 'No' 'No' 'Maybe' 'Maybe' 'Maybe'
 'Maybe' 'Maybe' 'Yes' 'Yes' 'Yes' 'Maybe' 'Yes' 'Yes' 'Yes' 'Maybe' 'Yes'
 'Maybe' 'Maybe' 'Maybe' 'Yes' 'Maybe' 'Yes' 'Maybe' 'Maybe' 'Maybe' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Maybe' 'Yes' 'Maybe' 'No' 'No' 'Yes'
 'Maybe' 'Yes' 'Yes' 'Maybe' 'No' 'Maybe' 'Maybe' 'Maybe' 'Yes' 'Maybe'
 'Maybe' 'Yes' 'Yes' 'Maybe' 'Yes' 'Yes' 'No' 'Maybe' 'Yes' 'Yes' 'Yes'
 'Yes' 'Maybe' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Maybe' 'Maybe'
 'Yes' 'No' 'Yes' 'Maybe' 'No' 'Yes' 'No' 'Maybe' 'No' 'Yes' 'Maybe'
 'Maybe' 'Yes' 'Maybe' 'Maybe' 'Yes' 'Yes' 'Maybe' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'Maybe' 'Yes' 'No' 'Yes'
 'Maybe' 'No' 'No' 'Maybe' 'Yes' 'Maybe' 'Maybe' 'Maybe' 'Maybe' 'Maybe'
 'Maybe' 'No' 'No' 'Maybe' 'Yes' 'Maybe' 'Maybe' 'Maybe' 'No' 'No' 'Maybe'
 'Yes' 'Yes' 'No' 'Yes' 'Maybe' 'Yes' 'Maybe' 'Maybe' '

In [25]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(X[:, 1:2])
X[:, 1:2] = imputer.transform(X[:, 1:2])

In [28]:
print(X)

[['Male' 'Indian' 24 'Traditional food' 'Fresh Juice']
 ['Female' 'Indian' 22 'Western Food' 'Carbonated drinks']
 ['Male' 'Indian' 31 'Western Food' 'Fresh Juice']
 ...
 ['Male' 'Indian' 25 'Traditional food' 'Fresh Juice']
 ['Male' 'Indian' 27 'Traditional food' 'Fresh Juice']
 ['Male' 'Indian' 27 'Traditional food' 'Fresh Juice']]


In [29]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct1 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse=False), [0,1,3,4])], remainder='passthrough')
X = np.array(ct1.fit_transform(X))

In [36]:
print(X[0])

[0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 24]


In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [33]:
print(Y)

[0 2 0 0 0 2 2 2 2 2 1 2 0 2 2 0 1 1 0 0 0 0 0 2 2 2 0 2 2 2 0 2 0 0 0 2 0
 2 0 0 0 2 2 2 2 2 2 2 0 2 0 1 1 2 0 2 2 0 1 0 0 0 2 0 0 2 2 0 2 2 1 0 2 2
 2 2 0 2 2 1 1 2 2 1 0 0 2 1 2 0 1 2 1 0 1 2 0 0 2 0 0 2 2 0 2 2 2 2 2 2 2
 1 1 1 2 2 0 2 1 2 0 1 1 0 2 0 0 0 0 0 0 1 1 0 2 0 0 0 1 1 0 2 2 1 2 0 2 0
 0 0 2 2 2 2 2 0 2 0 0 0 0 1 0 0 0 0 2 1 2 2 1 2 0 2 1 0 0 2 0 1 0 0 0 0 2
 0 2 0 2 1 2 2 0 0 0 1 1 1 0 0 0 2 1 1 0 0 0 1 0 1 1 2 1 0 0 0 0 1 0 2 0 1
 0 0 2 2 0 2 1 0 0 0 2 0 1 0 2 2 0 0 2 2 0 2 0 2 1 1 0 2 0 2 0 0 1 0 2 2 1
 2 1 0 2 1 2 2 2 0 2 0 2 0 0 0 0 0 2 2 2 0 0 0 1 2 2 2 2 1]


In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

In [46]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,-1 :] = sc.fit_transform(X_train[:,-1 :])
X_test[:, -1:] = sc.transform(X_test[:, -1:])

In [47]:
print(X_train)

[[1.0 0.0 0.0 ... 0.0 1.0 -0.556415510492697]
 [0.0 1.0 0.0 ... 0.0 1.0 -1.9525126095471002]
 [1.0 0.0 0.0 ... 0.0 1.0 1.1189010083725868]
 ...
 [1.0 0.0 0.0 ... 0.0 1.0 -1.021781210177498]
 [0.0 1.0 0.0 ... 0.0 1.0 -1.114854350114458]
 [0.0 1.0 0.0 ... 0.0 1.0 -0.556415510492697]]
